"use client";

import { Amplify } from "aws-amplify";

// Configure Amplify once at the app boundary.
// amplify_outputs.json is generated by `npx ampx sandbox` or a production
// Amplify Console deployment. Until then the UI runs in preview mode.
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const outputs = require("../../../amplify_outputs.json");
  Amplify.configure(outputs, { ssr: true });
} catch {
  console.info(
    "[AmplifyProvider] amplify_outputs.json not found — running in UI-preview mode. " +
    "Run `npx ampx sandbox` to connect a live backend."
  );
}

export function AmplifyProvider({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
